version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    environment:
      - CASSANDRA_CLUSTER_NAME=FinLimitCluster
      - CASSANDRA_DC=datacenter1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  app:
    image: finlimit-app:latest
    container_name: finlimit-app
    restart: always
    depends_on:
      - postgres
      - cassandra
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_CASSANDRA_CONTACT_POINTS: cassandra
      SPRING_CASSANDRA_PORT: 9042
      SPRING_CASSANDRA_KEYSPACE_NAME: ervy_keyspace
      SPRING_CASSANDRA_LOCAL_DATACENTER: datacenter1
      KEY_API: ${KEY_API}
    ports:
      - "8080:8080"
    networks:
      - finlimit_network

volumes:
  postgres_data:
  cassandra_data:

networks:
  finlimit_network:
    driver: bridge